# Generated by Django 5.2.2 on 2025-06-08 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=12)),
                ('overview', models.TextField()),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=30)),
                ('zip', models.CharField(max_length=8)),
                ('dob', models.CharField(max_length=12)),
                ('age', models.CharField(max_length=3)),
                ('email', models.CharField(max_length=20)),
                ('degree', models.CharField(max_length=20)),
                ('profile', models.ImageField(upload_to='profile_images/')),
            ],
        ),
    ]
