# Generated by Django 5.2.2 on 2025-06-08 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicdetails', '0002_alter_basic_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
