# Generated by Django 5.2.2 on 2025-06-09 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Main',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(blank=True, max_length=100, null=True)),
                ('job', models.CharField(blank=True, max_length=50, null=True)),
                ('experience', models.TextField(blank=True, null=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='cover_images/')),
                ('linkedin', models.TextField(max_length=300)),
                ('edu1_name', models.CharField(max_length=250)),
                ('edu1_desc', models.TextField()),
                ('edu2_name', models.CharField(max_length=250)),
                ('edu2_desc', models.TextField()),
                ('edu3_name', models.CharField(max_length=250)),
                ('edu3_desc', models.TextField()),
                ('project1_title', models.CharField(blank=True, max_length=250, null=True)),
                ('project1_technology', models.CharField(blank=True, max_length=300, null=True)),
                ('project1_desc', models.TextField(blank=True, null=True)),
                ('project2_title', models.CharField(blank=True, max_length=250, null=True)),
                ('project2_technology', models.CharField(blank=True, max_length=300, null=True)),
                ('project2_desc', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
