# Generated by Django 5.2.2 on 2025-06-10 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maindetails', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='main',
            name='cover_image',
        ),
    ]
