# Generated by Django 5.2.2 on 2025-06-21 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindetails', '0002_remove_main_cover_image'),
        ('users', '0003_remove_user_mobile_remove_user_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='main',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
