# Generated by Django 5.2.2 on 2025-06-21 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maindetails', '0003_main_user'),
        ('users', '0003_remove_user_mobile_remove_user_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='main',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.user'),
        ),
    ]
