# Generated by Django 5.2.2 on 2025-06-08 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicdetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basic',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='profile_images/'),
        ),
    ]
