# Generated by Django 5.2.2 on 2025-06-10 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basicdetails', '0003_alter_basic_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='basic',
            name='bio',
            field=models.CharField(default=6351327959, max_length=100),
            preserve_default=False,
        ),
    ]
