# Generated by Django 5.2.2 on 2025-06-10 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basicdetails', '0004_basic_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basic',
            name='profile',
        ),
    ]
